sudo: false
cache:
  directories:
    - $HOME/.smartdatasets
    - $HOME/download
    - $HOME/.cache/pip

language: python
python:
  - "3.3"
  - "3.4"

# command to install dependencies
before_install:
# Install miniconda to avoid compiling scipy
  - mkdir -p download
  - cd download
  - wget -c http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - cd ..
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes conda

install:
  - if [[ $TRAVIS_PYTHON_VERSION == '3.3' ]]; then conda create --yes -q -n pyenv mkl python=3.3 numpy scipy nose pyparsing pip flake8 six pep8 pyflakes; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '3.4' ]]; then conda create --yes -q -n pyenv mkl python=3.4 numpy scipy nose pyparsing pip flake8 six pep8 pyflakes; fi
  - source activate pyenv
  - curl -O https://raw.githubusercontent.com/mila-udem/blocks/master/req-travis-conda.txt
  - conda install -q --yes python=$TRAVIS_PYTHON_VERSION mkl --file req-travis-conda.txt
  - pip install theano
  - pip install https://github.com/SMART-Lab/smartlearner/archive/master.zip
  - pip install -q -r https://raw.githubusercontent.com/mila-udem/blocks/master/req-travis-pip.txt
  - pip install -q git+git://github.com/mila-udem/blocks.git -r https://raw.githubusercontent.com/mila-udem/blocks/master/requirements.txt
  - pip install .

# command to run tests, e.g. python setup.py test
script:
  - nosetests -sv
